apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Demander 2 Go de stockage
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13  # Utilise l'image officielle PostgreSQL
          env:
            - name: POSTGRES_USER
              value: "user"  # Nom de l'utilisateur de la base de données
            - name: POSTGRES_PASSWORD
              value: "password"  # Mot de passe de l'utilisateur
            - name: POSTGRES_DB
              value: "nextjsdb"  # Nom de la base de données
          ports:
            - containerPort: 5432  # Le port PostgreSQL
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data  # Persister les données PostgreSQL

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc  # Référence à un PVC pour persister les données

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP  # Service interne pour que Next.js puisse s'y connecter


