apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  labels:
    app: nextjs
spec:
  selector:
    app: nextjs  # Ce selector correspond aux labels du pod dans le Deployment
  ports:
    - protocol: TCP
      port: 3000         # Le port exposé par le Service
      targetPort: 3000   # Le port utilisé dans le conteneur
      nodePort: 32000    # Le port utilisé sur le noeud pour accéder au Service (optionnel, Kubernetes l'attribuera automatiquement si omis)
  type: NodePort
